"""Shared constants for the Astar Island solver."""

GRID_SIZE = 40
NUM_CLASSES = 6
DEFAULT_TOTAL_QUERIES = 50

CLASS_EMPTY = 0
CLASS_SETTLEMENT = 1
CLASS_PORT = 2
CLASS_RUIN = 3
CLASS_FOREST = 4
CLASS_MOUNTAIN = 5

INTERNAL_EMPTY = 0
INTERNAL_SETTLEMENT = 1
INTERNAL_PORT = 2
INTERNAL_RUIN = 3
INTERNAL_FOREST = 4
INTERNAL_MOUNTAIN = 5
INTERNAL_OCEAN = 10
INTERNAL_PLAINS = 11

TERRAIN_TO_CLASS = {
    INTERNAL_EMPTY: CLASS_EMPTY,
    INTERNAL_OCEAN: CLASS_EMPTY,
    INTERNAL_PLAINS: CLASS_EMPTY,
    INTERNAL_SETTLEMENT: CLASS_SETTLEMENT,
    INTERNAL_PORT: CLASS_PORT,
    INTERNAL_RUIN: CLASS_RUIN,
    INTERNAL_FOREST: CLASS_FOREST,
    INTERNAL_MOUNTAIN: CLASS_MOUNTAIN,
}

STATIC_TERRAIN_CODES = (INTERNAL_OCEAN, INTERNAL_MOUNTAIN)
DYNAMIC_CLASSES = (CLASS_SETTLEMENT, CLASS_PORT, CLASS_RUIN, CLASS_FOREST)

TERRAIN_CODES = (
    INTERNAL_EMPTY,
    INTERNAL_OCEAN,
    INTERNAL_PLAINS,
    INTERNAL_SETTLEMENT,
    INTERNAL_PORT,
    INTERNAL_RUIN,
    INTERNAL_FOREST,
    INTERNAL_MOUNTAIN,
)
