"""
Calibrate the coherence modulation strength in solution_diamond.py.

Method:
- verify that local scoring matches stored API analysis scores
- use only rounds with full local query history (`history_replay`)
- grid search a single multiplier applied to the coherence modulation strength
- optimize weighted total score, which matches the leaderboard objective

This is the closest available approximation to a real historical replay:
- official score formula
- real ground truth
- real stored observations
- current Diamond post-observation prediction pipeline

Constraint:
- the historical queries were generated by a previous solver, not the current
  `solution_diamond.py` query planner, because completed rounds cannot be
  replayed with `/simulate`.
"""

from __future__ import annotations

import json
import math
import time
from pathlib import Path

import numpy as np

import backtest_diamond_full as bt
import solution_diamond as diamond


HISTORY_ROOT = Path(__file__).with_name("history")
OUTPUT_PATH = Path(__file__).with_name("calibrate_coherence_strength_results.json")


def score_prediction(gt: np.ndarray, pred: np.ndarray, grid: np.ndarray) -> float:
    eps = 1e-12
    gt = np.clip(np.asarray(gt, dtype=float), eps, 1.0)
    pred = np.clip(np.asarray(pred, dtype=float), eps, 1.0)
    grid = np.asarray(grid, dtype=int)

    cell_kl = np.sum(gt * np.log(gt / pred), axis=-1)
    cell_entropy = -np.sum(gt * np.log(gt), axis=-1)
    dynamic_mask = ~np.isin(grid, [10, 5])
    masked_entropy = cell_entropy * dynamic_mask
    total_entropy = float(masked_entropy.sum())

    if total_entropy > 0:
        wkl = float((masked_entropy * cell_kl).sum() / total_entropy)
    else:
        dynamic_kls = cell_kl[dynamic_mask]
        wkl = float(dynamic_kls.mean()) if dynamic_kls.size else float(cell_kl.mean())

    return max(0.0, min(100.0, 100.0 * math.exp(-3.0 * wkl)))


def verify_local_scoring() -> dict:
    round_rows = []
    all_diffs = []

    for manifest_path in sorted(HISTORY_ROOT.glob("*/manifest.json")):
        manifest = json.loads(manifest_path.read_text())
        round_id = manifest["round_id"]
        round_number = manifest.get("round_metadata", {}).get("round_number")
        predictions = manifest.get("predictions", {})
        ground_truth = manifest.get("ground_truth", {})
        analyses = manifest.get("analyses", {})
        initial_states = {str(item["seed_index"]): item for item in manifest.get("initial_states", [])}

        diffs = []
        for seed_index, pred_path in predictions.items():
            if seed_index not in ground_truth or seed_index not in analyses or seed_index not in initial_states:
                continue

            pred = np.load(HISTORY_ROOT / round_id / pred_path)
            gt = np.load(HISTORY_ROOT / round_id / ground_truth[seed_index])
            grid = np.load(HISTORY_ROOT / round_id / initial_states[seed_index]["grid_path"])
            local_score = score_prediction(gt, pred, grid)
            api_score = float(analyses[seed_index]["score"])
            diff = abs(local_score - api_score)
            diffs.append(diff)
            all_diffs.append(diff)

        if diffs:
            round_rows.append(
                {
                    "round_number": round_number,
                    "mean_abs_diff": float(np.mean(diffs)),
                    "max_abs_diff": float(np.max(diffs)),
                    "num_seeds": len(diffs),
                }
            )

    return {
        "rounds": round_rows,
        "global_mean_abs_diff": float(np.mean(all_diffs)) if all_diffs else None,
        "global_max_abs_diff": float(np.max(all_diffs)) if all_diffs else None,
        "num_seed_scores_checked": len(all_diffs),
    }


def replay_manifests() -> list[dict]:
    manifests = []
    for manifest_path in sorted(HISTORY_ROOT.glob("*/manifest.json")):
        manifest = json.loads(manifest_path.read_text())
        if len(manifest.get("queries", [])) > 0 and manifest.get("ground_truth"):
            manifests.append(manifest)
    manifests.sort(key=lambda item: item.get("round_metadata", {}).get("round_number", 0))
    return manifests


def local_round_data(manifest: dict) -> dict:
    round_metadata = manifest.get("round_metadata", {})
    if round_metadata.get("initial_states"):
        return {
            "round_number": round_metadata.get("round_number"),
            "round_weight": round_metadata.get("round_weight", 1.0),
            "initial_states": round_metadata["initial_states"],
        }

    initial_states = []
    for item in manifest.get("initial_states", []):
        grid = np.load(HISTORY_ROOT / manifest["round_id"] / item["grid_path"]).tolist()
        initial_states.append(
            {
                "seed_index": item["seed_index"],
                "grid": grid,
                "settlements": item.get("settlements", []),
            }
        )
    return {
        "round_number": round_metadata.get("round_number"),
        "round_weight": round_metadata.get("round_weight", 1.0),
        "initial_states": initial_states,
    }


def local_ground_truth_by_seed(manifest: dict) -> dict[int, dict]:
    analyses = manifest.get("analyses", {})
    result = {}
    for seed_index, path in manifest.get("ground_truth", {}).items():
        result[int(seed_index)] = {
            "ground_truth": np.load(HISTORY_ROOT / manifest["round_id"] / path),
            "api_score": analyses.get(str(seed_index), {}).get("score"),
        }
    return result


def evaluate_multiplier(
    multiplier: float,
    manifests: list[dict],
    transition_table: dict | None,
    simple_prior: dict | None,
    opt_tables: dict | None,
    alpha: float,
) -> dict:
    diamond.COHERENCE_STRENGTH_MULTIPLIER = multiplier
    bt.diamond.COHERENCE_STRENGTH_MULTIPLIER = multiplier

    rounds = []
    weighted_total = 0.0

    for manifest in manifests:
        result = bt.run_history_replay_round(
            round_id=manifest["round_id"],
            round_data=local_round_data(manifest),
            manifest=manifest,
            transition_table=transition_table,
            simple_prior=simple_prior,
            opt_tables=opt_tables,
            alpha=alpha,
            ground_truth_by_seed=local_ground_truth_by_seed(manifest),
        )
        rounds.append(result)
        weighted_total += result["weighted_round_score"]

    mean_round_score = float(np.mean([item["round_score"] for item in rounds]))
    weighted_avg_score = float(
        np.sum([item["round_score"] * item["round_weight"] for item in rounds])
        / np.sum([item["round_weight"] for item in rounds])
    )

    return {
        "multiplier": round(multiplier, 6),
        "num_rounds": len(rounds),
        "weighted_total_score": round(weighted_total, 6),
        "weighted_average_score": round(weighted_avg_score, 6),
        "mean_round_score": round(mean_round_score, 6),
        "rounds": [
            {
                "round_number": item["round_number"],
                "round_score": item["round_score"],
                "weighted_round_score": item["weighted_round_score"],
                "world_type": item.get("world_type"),
                "spatial_coherence": item.get("spatial_coherence"),
            }
            for item in rounds
        ],
    }


def search_multipliers(
    candidates: list[float],
    manifests: list[dict],
    transition_table: dict | None,
    simple_prior: dict | None,
    opt_tables: dict | None,
    alpha: float,
) -> list[dict]:
    results = []
    for multiplier in candidates:
        results.append(
            evaluate_multiplier(
                multiplier=multiplier,
                manifests=manifests,
                transition_table=transition_table,
                simple_prior=simple_prior,
                opt_tables=opt_tables,
                alpha=alpha,
            )
        )
    results.sort(key=lambda item: item["weighted_total_score"], reverse=True)
    return results


def main() -> None:
    transition_table, simple_prior = diamond.load_calibration()
    _ = diamond.load_calibration_by_type()
    opt_tables = diamond.load_optimized_calibration()
    learning = diamond.load_learning_state()
    alpha = float(learning.get("alpha", diamond.DEFAULT_ALPHA))
    original_multiplier = diamond.COHERENCE_STRENGTH_MULTIPLIER

    manifests = replay_manifests()
    if not manifests:
        raise SystemExit("Fant ingen replay-runder med lagrede queries.")

    scoring_validation = verify_local_scoring()

    coarse = [round(x, 2) for x in np.arange(0.0, 8.01, 0.50)]
    coarse_results = search_multipliers(
        candidates=coarse,
        manifests=manifests,
        transition_table=transition_table,
        simple_prior=simple_prior,
        opt_tables=opt_tables,
        alpha=alpha,
    )
    coarse_best = coarse_results[0]["multiplier"]

    fine_lo = max(0.0, coarse_best - 1.0)
    fine_hi = coarse_best + 1.0
    fine = [round(x, 3) for x in np.arange(fine_lo, fine_hi + 0.001, 0.10)]
    fine_results = search_multipliers(
        candidates=fine,
        manifests=manifests,
        transition_table=transition_table,
        simple_prior=simple_prior,
        opt_tables=opt_tables,
        alpha=alpha,
    )
    fine_best = fine_results[0]["multiplier"]

    final_lo = max(0.0, fine_best - 0.2)
    final_hi = fine_best + 0.2
    final = [round(x, 3) for x in np.arange(final_lo, final_hi + 0.001, 0.05)]
    final_results = search_multipliers(
        candidates=final,
        manifests=manifests,
        transition_table=transition_table,
        simple_prior=simple_prior,
        opt_tables=opt_tables,
        alpha=alpha,
    )
    best = final_results[0]

    baseline_1 = next(item for item in fine_results if abs(item["multiplier"] - 1.0) < 1e-9) if any(abs(item["multiplier"] - 1.0) < 1e-9 for item in fine_results) else evaluate_multiplier(1.0, manifests, transition_table, simple_prior, opt_tables, alpha)
    baseline_0 = next(item for item in coarse_results if abs(item["multiplier"] - 0.0) < 1e-9)

    payload = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "alpha": alpha,
        "replay_round_numbers": [manifest.get("round_metadata", {}).get("round_number") for manifest in manifests],
        "scoring_validation": scoring_validation,
        "current_defaults": {
            "multiplier": original_multiplier,
            "base_scale": diamond.COHERENCE_BASE_SCALE,
            "max_adjustment": diamond.COHERENCE_MAX_ADJUSTMENT,
        },
        "baselines": {
            "multiplier_0_0": baseline_0,
            "multiplier_1_0": baseline_1,
        },
        "coarse_results": coarse_results,
        "fine_results": fine_results,
        "final_results": final_results,
        "best": best,
    }
    OUTPUT_PATH.write_text(json.dumps(payload, indent=2, default=str))
    diamond.COHERENCE_STRENGTH_MULTIPLIER = original_multiplier
    bt.diamond.COHERENCE_STRENGTH_MULTIPLIER = original_multiplier

    print("Scoring validation:")
    print(
        f"  mean_abs_diff={scoring_validation['global_mean_abs_diff']:.6f} "
        f"max_abs_diff={scoring_validation['global_max_abs_diff']:.6f} "
        f"n={scoring_validation['num_seed_scores_checked']}"
    )
    print(f"Replay rounds: {payload['replay_round_numbers']}")
    print(f"Baseline multiplier 0.0: weighted_total={baseline_0['weighted_total_score']:.4f} mean={baseline_0['mean_round_score']:.4f}")
    print(f"Baseline multiplier 1.0: weighted_total={baseline_1['weighted_total_score']:.4f} mean={baseline_1['mean_round_score']:.4f}")
    print(f"Best multiplier: {best['multiplier']:.3f}")
    print(f"  weighted_total={best['weighted_total_score']:.4f} mean={best['mean_round_score']:.4f} weighted_avg={best['weighted_average_score']:.4f}")
    print(f"Saved to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
